// src/constants/lifecycleStages.ts
import type { LifecycleStageKey } from '@/types/aiService'; // Ensure path is correct

export const STAGE_LABELS: Record<LifecycleStageKey, string> = {
  businessUseCaseGeneration: "Business Use Case Generation",
  dataHandling: "Data Handling",
  modelArchitectureExploration: "Model Architecture Exploration",
  modelTraining: "Model Training",
  modelOperation: "Model Operation (Inference)", // Matched your mapping.txt
  modelEndOfLife: "Model End-of-Life",
  materialExtraction: "Material Extraction",
  hardwareManufacturing: "Hardware Manufacturing",
  hardwareTransport: "Hardware Transport",
  AISystemInstallation: "AI System Installation",
  // Note: "AI System Hardware Disposal / Recyling" from mapping.txt isn't in cgsaem.schema.json's required stages.
  // If it's a distinct stage, it needs to be added to LifecycleStageKey and the schema.
  // For now, assuming it's covered by modelEndOfLife or simi
  // lar.
};

export const SOFTWARE_STAGE_DESCRIPTIONS: Partial<Record<LifecycleStageKey, string>> = {
    businessUseCaseGeneration: "CO₂ emissions from activties of clariying / detailing business requirements for promising AI services (e.g. Total emitted CO2 for video-conferencing meetings) ",
    dataHandling: "Emissions from data ingestion, cleaning, transformation, and storage operations.",
    modelArchitectureExploration: "CO₂ impact from running multiple experiments (pre-training run)s to compare and validate model architectures.",
    modelTraining: "Emissions due to GPU/CPU usage during full-scale training and periodic retraining.",
    modelOperation: "Associated emitted CO₂ from both idle and inference workloads during deployment, use and monitoring of an AI service.", // Note 'modelOperation' vs 'modelOperation (Inference)'
    modelEndOfLife: "Emissions from archiving, and decommissioning model infrastructure and resources."
};

export const HARDWARE_STAGE_DESCRIPTIONS: Partial<Record<LifecycleStageKey, string>> = {
    materialExtraction: "CO₂ emissions from mining and refining ores into metals for AI hardware components.",
    hardwareManufacturing: "Impact of fabricating servers, chips, racks, and cooling infrastructure from raw or pre-processed materials.",
    hardwareTransport: "Emissions generated by shipping hardware and parts from factories to data centers or edge sites.",
    AISystemInstallation: "Energy and CO₂ from rack assembly, cabling, and initial power-up during hardware installation."
};

export const getStageDescription = (stageKey: LifecycleStageKey): string | undefined => {
  return SOFTWARE_STAGE_DESCRIPTIONS[stageKey] || HARDWARE_STAGE_DESCRIPTIONS[stageKey];
};